M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu20.04.1} date čet 16 nov 2023 21:13:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-16T21:13:01+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
%
G90
G05
T1
X115.57Y-77.135
X115.57Y-84.135
X125.73Y-77.135
X125.73Y-84.135
T0
M30
